# Generated by Django 5.2.10 on 2026-01-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_time', models.DateTimeField()),
                ('player_tag', models.CharField(max_length=255)),
                ('enemy_tag', models.CharField(max_length=255)),
                ('starting_trophies', models.IntegerField()),
                ('trophy_change', models.IntegerField()),
                ('raw_data', models.JSONField()),
            ],
            options={
                'ordering': ['player_tag', 'battle_time'],
            },
        ),
    ]
