# Generated by Django 5.2.10 on 2026-03-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crstats', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlelog',
            name='enemy_exp_lvl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlelog',
            name='enemy_tower',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlelog',
            name='player_exp_lvl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlelog',
            name='player_tower',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
