# Generated by Django 5.2.10 on 2026-06-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crstats', '0003_battlelog_enemy_exp_lvl_battlelog_enemy_tower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlelog',
            name='enemy_tower',
        ),
        migrations.RemoveField(
            model_name='battlelog',
            name='player_tower',
        ),
    ]
